#!/usr/bin/env bash
set -euo pipefail

# WWFI reverse proxy generator (single public IP, multiple domains via SNI).
#
# Usage:
#   generate_reverse_proxy.sh [--engine nginx|caddy] [--cert-dir DIR]
#       [--base-dir DIR] [--reload] domain=backend [domain=backend ...]
#
# Examples:
#   scripts/generate_reverse_proxy.sh demo.local=127.0.0.1:8000 shop.local=127.0.0.1:8080
#   scripts/generate_reverse_proxy.sh --engine caddy demo.local=127.0.0.1:8000
#   scripts/generate_reverse_proxy.sh --reload demo.local=wwfi:8000 shop.local=wwfi:8080

ENGINE="nginx"
CERT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/certs"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RELOAD=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --engine)
      ENGINE="$2"; shift 2 ;;
    --cert-dir)
      CERT_DIR="$2"; shift 2 ;;
    --base-dir)
      BASE_DIR="$2"; shift 2 ;;
    --reload)
      RELOAD=1; shift ;;
    *)
      break ;;
  esac
done

NGINX_SITES="$BASE_DIR/configs/sites-available"
NGINX_ENABLED="$BASE_DIR/configs/sites-enabled"
CADDYFILE="$BASE_DIR/configs/Caddyfile"

mkdir -p "$NGINX_SITES" "$NGINX_ENABLED"
: > "$CADDYFILE"
: > /tmp/wwfi-reload-list.txt

if [[ $# -eq 0 ]]; then
  echo "ERROR: no domain=backend pairs provided" >&2
  exit 1
fi

generate_nginx() {
  local domain="$1" backend="$2"
  local port="${backend##*:}"
  local upstream="${backend%:*}"
  local conf="$NGINX_SITES/$domain.conf"
  cat > "$conf" <<EOF
# Generated by wwfi generate_reverse_proxy.sh
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name $domain;

    ssl_certificate     $CERT_DIR/$domain.crt;
    ssl_certificate_key $CERT_DIR/$domain.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://$upstream:$port;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
EOF
  ln -sfn "$conf" "$NGINX_ENABLED/$domain.conf"
  echo "$conf"
}

generate_caddy() {
  local domain="$1" backend="$2"
  cat >> "$CADDYFILE" <<EOF

$domain {
    tls $CERT_DIR/$domain.crt $CERT_DIR/$domain.key
    reverse_proxy $backend
}
EOF
  echo "$CADDYFILE"
}

reload_engine() {
  if [[ "$RELOAD" -eq 0 ]]; then
    return 0
  fi
  case "$ENGINE" in
    nginx)
      nginx -t && (nginx -s reload || systemctl reload nginx || service nginx reload) ;;
    caddy)
      caddy validate --config "$CADDYFILE" && (systemctl reload caddy || caddy reload --config "$CADDYFILE") ;;
  esac
}

for pair in "$@"; do
  domain="${pair%%=*}"
  backend="${pair#*=}"
  case "$ENGINE" in
    nginx) generate_nginx "$domain" "$backend" ;;
    caddy) generate_caddy "$domain" "$backend" ;;
    *) echo "ERROR: unknown engine '$ENGINE' (use nginx or caddy)" >&2; exit 1 ;;
  esac
done

reload_engine

echo "[wwfi] generated reverse proxy configs ($ENGINE) for: $*"
echo "[wwfi] cert dir: $CERT_DIR"
echo "[wwfi] nginx sites: $NGINX_SITES"
echo "[wwfi] caddy file: $CADDYFILE"