#!/usr/bin/env bash
set -euo pipefail

# WWFI DoH/DoT local resolver bridge.
#
# Sets up encrypted upstream resolution for the local dnsmasq resolver:
#   - DoT: stubby validates and encrypts upstream queries
#   - DoH: cloudflared HTTPS proxy (optional; choose one)
#
# Architecture:
#   client -> dnsmasq (local .local records, port 53)
#                  |-> 127.0.0.1:5353 stubby        (DoT)
#                  |-> 127.0.0.1:5053 cloudflared   (DoH)
#
# Usage:
#   sudo scripts/setup_doh_dot.sh dot
#   sudo scripts/setup_doh_dot.sh doh

MODE="${1:-dot}"
STUBBY_YML="/etc/stubby/stubby.yml"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "This script must be run as root (sudo)." >&2
  exit 1
fi

case "$MODE" in
  dot)
    echo "[doh-dot] installing stubby (DoT)"
    apt-get update
    apt-get install -y stubby
    if [[ -f "$STUBBY_YML" ]]; then
      cp "$STUBBY_YML" "$STUBBY_YML.bak"
    fi
    cat > "$STUBBY_YML" <<'EOF'
stubby:
  listen_addresses:
    - 127.0.0.1@5353
  tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
  dns_transport_list:
    - GETDNS_TRANSPORT_TLS
  upstream_recursive_servers:
    - address_data: 1.1.1.1
      tls_auth_name: cloudflare-dns.com
    - address_data: 8.8.8.8
      tls_auth_name: dns.google
EOF
    systemctl restart stubby || service stubby restart
    UPSTREAM_SPEC="127.0.0.1#5353"
    ;;
  doh)
    echo "[doh-dot] installing cloudflared (DoH)"
    apt-get update
    apt-get install -y curl
    if ! command -v cloudflared >/dev/null 2>&1; then
      curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | dd of=/usr/share/keyrings/cloudflare-main.gpg
      . /etc/os-release
      echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $VERSION_CODENAME main" > /etc/apt/sources.list.d/cloudflared.list
      apt-get update && apt-get install -y cloudflared
    fi
    pkill -f "cloudflared proxy-dns" 2>/dev/null || true
    nohup cloudflared proxy-dns --upstream "https://1.1.1.1/dns-query" --port 5053 --address 127.0.0.1 >/dev/null 2>&1 &
    UPSTREAM_SPEC="127.0.0.1#5053"
    ;;
  *)
    echo "Usage: $0 {dot|doh}" >&2
    exit 1
    ;;
esac

cat > /etc/dnsmasq.d/wwfi-upstream.conf <<EOF
# WWFI encrypted upstream (generated by setup_doh_dot.sh $MODE)
server=$UPSTREAM_SPEC
server=$UPSTREAM_SPEC
EOF

systemctl restart dnsmasq || service dnsmasq restart || true

cat <<'EOF'
[doh-dot] complete.

Test DoT via stubby directly:
  dig @127.0.0.1 -p 5353 example.com

Test the DoH bridge directly (when MODE=doh):
  dig @127.0.0.1 -p 5053 cloudflare.com +noall +answer

Test the full encrypted resolver (upstream + local .local records):
  dig @127.0.0.1 demo.local +short
  dig @127.0.0.1 example.com

If your dig supports DoH natively:
  dig @127.0.0.1 demo.local +https
EOF